name: Backup Posts to Google Drive

on:
  push:
    branches: [ main ]
    paths:
      - 'posts/**'

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Upload posts to Google Drive
      uses: Jodebu/upload-to-drive@v1
      with:
        target: posts
        credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
        folder: ${{ secrets.GDRIVE_FOLDER_ID }}
        
  # TODO: Add email notification setup
  # notify-failure:
  #   runs-on: ubuntu-latest
  #   needs: backup
  #   if: failure()
  #   
  #   steps:
  #   - name: Send failure notification
  #     uses: dawidd6/action-send-mail@v3
  #     with:
  #       server_address: smtp.gmail.com
  #       server_port: 587
  #       username: ${{ secrets.EMAIL_USERNAME }}
  #       password: ${{ secrets.EMAIL_PASSWORD }}
  #       subject: "Blog Backup Failed - ${{ github.repository }}"
  #       body: |
  #         The automated backup of blog posts to Google Drive has failed.
  #         
  #         Repository: ${{ github.repository }}
  #         Branch: ${{ github.ref }}
  #         Commit: ${{ github.sha }}
  #         Workflow: ${{ github.workflow }}
  #         
  #         Please check the GitHub Actions logs for more details:
  #         ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  #       to: ${{ secrets.EMAIL_TO }}
  #       from: Blog Backup System