name: Backup Posts to Google Drive

on:
  push:
    branches: [ main ]
    paths:
      - 'posts/**'

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Create posts backup archive
      run: |
        # Create a timestamped zip file of the posts directory
        TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        zip -r "posts-backup-${TIMESTAMP}.zip" posts/
        echo "BACKUP_FILE=posts-backup-${TIMESTAMP}.zip" >> $GITHUB_ENV
        
    - name: Upload to Google Drive
      uses: mathisve/gdrive-upload-action@main
      with:
        filename: ${{ env.BACKUP_FILE }}
        credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
        folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
        
  notify-failure:
    runs-on: ubuntu-latest
    needs: backup
    if: failure()
    
    steps:
    - name: Send webhook notification
      run: |
        curl -X POST "https://hooks.zapier.com/hooks/catch/107299/u3il2z9/" \
          -H "Content-Type: application/json" \
          -d '{
            "event": "backup_failed",
            "repository": "${{ github.repository }}",
            "branch": "${{ github.ref_name }}",
            "commit": "${{ github.sha }}",
            "workflow": "${{ github.workflow }}",
            "run_id": "${{ github.run_id }}",
            "actor": "${{ github.actor }}",
            "timestamp": "${{ github.event.head_commit.timestamp }}",
            "logs_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "message": "The automated backup of blog posts to Google Drive has failed. Check the GitHub Actions logs for details."
          }'